/** Permission keys shared with the Identity service. */
export const ADMIN_PERMISSIONS = {
  usersView: 'Permissions.Users.View',
  usersCreate: 'Permissions.Users.Create',
  usersEdit: 'Permissions.Users.Edit',
  usersDelete: 'Permissions.Users.Delete',
  usersChangePassword: 'Permissions.Users.ChangePassword',
  usersActivate: 'Permissions.Users.Activate',
  usersConfirmEmail: 'Permissions.Users.ConfirmEmail',
  rolesView: 'Permissions.Roles.View',
  rolesCreate: 'Permissions.Roles.Create',
  rolesEdit: 'Permissions.Roles.Edit',
  rolesDelete: 'Permissions.Roles.Delete',
  rolesManagePermissions: 'Permissions.Roles.ManagePermissions',
  permissionView: 'Permissions.Permissions.View',
  permissionCreate: 'Permissions.Permissions.Create',
  permissionEdit: 'Permissions.Permissions.Edit',
  permissionDelete: 'Permissions.Permissions.Delete',
  institutionsView: 'Permissions.Institutions.View',
  institutionsManage: 'Permissions.Institutions.Manage',
  coachingView: 'Permissions.Coaching.View',
  coachingManage: 'Permissions.Coaching.Manage',
  speedReadingView: 'Permissions.SpeedReading.View',
  speedReadingContentManage: 'Permissions.SpeedReading.ContentManage',
  speedReadingProgramManage: 'Permissions.SpeedReading.ProgramManage',
  speedReadingProgressView: 'Permissions.SpeedReading.ProgressView',
  speedReadingReportView: 'Permissions.SpeedReading.ReportView',
  speedReadingGamificationManage: 'Permissions.SpeedReading.GamificationManage',
  speedReadingSettingsManage: 'Permissions.SpeedReading.SettingsManage',
  supportView: 'Permissions.Support.View',
  supportReply: 'Permissions.Support.Reply',
  notificationTemplates: 'Permissions.Notifications.Templates',
  operationsView: 'Permissions.Operations.View'
} as const;
