// <auto-generated />
using Coaching.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Coaching.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CoachingDbContext))]
    [Migration("20260820213000_AddCoachingIdempotencyRecords")]
    partial class AddCoachingIdempotencyRecords
    {
    }
}
