using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SpeedReading.Infrastructure.Persistence;

#nullable disable

namespace SpeedReading.Infrastructure.Persistence.Migrations;

[DbContext(typeof(OwnedSpeedReadingDbContext))]
[Migration("20260921180000_AddPrivacyAssessmentOutbox")]
public sealed class AddPrivacyAssessmentOutbox : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE speed_reading."InboxState" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "MessageId" uuid NOT NULL,
                "ConsumerId" uuid NOT NULL,
                "LockId" uuid NOT NULL,
                "RowVersion" bytea NULL,
                "Received" timestamp with time zone NOT NULL,
                "ReceiveCount" integer NOT NULL,
                "ExpirationTime" timestamp with time zone NULL,
                "Consumed" timestamp with time zone NULL,
                "Delivered" timestamp with time zone NULL,
                "LastSequenceNumber" bigint NULL,
                CONSTRAINT "AK_InboxState_MessageId_ConsumerId" UNIQUE ("MessageId", "ConsumerId")
            );
            CREATE INDEX "IX_InboxState_Delivered"
                ON speed_reading."InboxState" ("Delivered");

            CREATE TABLE speed_reading."OutboxState" (
                "OutboxId" uuid PRIMARY KEY,
                "LockId" uuid NOT NULL,
                "RowVersion" bytea NULL,
                "Created" timestamp with time zone NOT NULL,
                "Delivered" timestamp with time zone NULL,
                "LastSequenceNumber" bigint NULL
            );
            CREATE INDEX "IX_OutboxState_Created"
                ON speed_reading."OutboxState" ("Created");

            CREATE TABLE speed_reading."OutboxMessage" (
                "SequenceNumber" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "EnqueueTime" timestamp with time zone NULL,
                "SentTime" timestamp with time zone NOT NULL,
                "Headers" text NULL,
                "Properties" text NULL,
                "InboxMessageId" uuid NULL,
                "InboxConsumerId" uuid NULL,
                "OutboxId" uuid NULL,
                "MessageId" uuid NOT NULL,
                "ContentType" character varying(256) NOT NULL,
                "MessageType" text NOT NULL,
                "Body" text NOT NULL,
                "ConversationId" uuid NULL,
                "CorrelationId" uuid NULL,
                "InitiatorId" uuid NULL,
                "RequestId" uuid NULL,
                "SourceAddress" character varying(256) NULL,
                "DestinationAddress" character varying(256) NULL,
                "ResponseAddress" character varying(256) NULL,
                "FaultAddress" character varying(256) NULL,
                "ExpirationTime" timestamp with time zone NULL,
                CONSTRAINT "FK_OutboxMessage_InboxState_InboxMessageId_InboxConsumerId"
                    FOREIGN KEY ("InboxMessageId", "InboxConsumerId")
                    REFERENCES speed_reading."InboxState" ("MessageId", "ConsumerId"),
                CONSTRAINT "FK_OutboxMessage_OutboxState_OutboxId"
                    FOREIGN KEY ("OutboxId") REFERENCES speed_reading."OutboxState" ("OutboxId")
            );
            CREATE INDEX "IX_OutboxMessage_EnqueueTime"
                ON speed_reading."OutboxMessage" ("EnqueueTime");
            CREATE INDEX "IX_OutboxMessage_ExpirationTime"
                ON speed_reading."OutboxMessage" ("ExpirationTime");
            CREATE UNIQUE INDEX "IX_OutboxMessage_InboxMessageId_InboxConsumerId_SequenceNumber"
                ON speed_reading."OutboxMessage" ("InboxMessageId", "InboxConsumerId", "SequenceNumber");
            CREATE UNIQUE INDEX "IX_OutboxMessage_OutboxId_SequenceNumber"
                ON speed_reading."OutboxMessage" ("OutboxId", "SequenceNumber");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DROP TABLE speed_reading."OutboxMessage";
            DROP TABLE speed_reading."InboxState";
            DROP TABLE speed_reading."OutboxState";
            """);
    }
}
